version: 0.2
phases:
  pre_build:
    commands:
      - $(aws ecr get-login --no-include-email --region us-east-1)
  build:
    commands:
      - docker build -t project-repository .
      - docker tag project-repository:latest 951061097896.dkr.ecr.us-east-1.amazonaws.com/project-repository:latest
  post_build:
    commands:
      - docker push 951061097896.dkr.ecr.us-east-1.amazonaws.com/project-repository:latest
