name: Build and Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1

      - name: Login to Amazon ECR
        id: login-ecr
        run: echo $(aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com)
      
      - name: Build and push Docker image to registry
        env:
          AWS_DEFAULT_REGION: us-east-1
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 951061097896.dkr.ecr.us-east-1.amazonaws.com
          docker build -t project-repository .
          docker tag project-repository:latest 951061097896.dkr.ecr.us-east-1.amazonaws.com/project-repository:latest
          docker push 951061097896.dkr.ecr.us-east-1.amazonaws.com/project-repository:latest
