name: Build and Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        run: echo $(aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com)
      
      - name: Build and push Docker image to registry
        env:
          AWS_DEFAULT_REGION: us-east-1
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 951061097896.dkr.ecr.us-east-1.amazonaws.com
          docker build -t project-repository .
          docker tag project-repository:latest 951061097896.dkr.ecr.us-east-1.amazonaws.com/project-repository:latest
          docker push 951061097896.dkr.ecr.us-east-1.amazonaws.com/project-repository:latest
  deploy:
      needs: build
      runs-on: ubuntu-latest
      steps:
        - name: Configure AWS credentials
          uses: aws-actions/configure-aws-credentials@v1
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: us-east-1
        
        - name: Deploy to ECS
          env:
            AWS_DEFAULT_REGION: us-east-1
          run: |
            aws ecs run-task \
              --cluster arn:aws:ecs:us-east-1:951061097896:cluster/dev-cluster \
              --task-definition arn:aws:ecs:us-east-1:951061097896:task-definition/api-task:5 \
              --network-configuration "awsvpcConfiguration={subnets=[subnet-09d261243dc7f37b1, subnet-0d486c7a14ccdc9bd, subnet-05f69ac405aa6bfab, subnet-050ff51feb258e609, subnet-028c5ecc9bc80f918, subnet-0e3a1cc52a18b4354],securityGroups=[sg-040efe0490d70439d,sg-0acf56aa7e12b2876,sg-0363551cc6cc364bc],assignPublicIp=ENABLED}" \
              --launch-type FARGATE \
              --count 1